window.VOCAB={
"A":[
["abolish","v","abschaffen, aufheben","Parliament voted to abolish the tax on books."],
["abortion","n","Schwangerschaftsabbruch","The law on abortion was debated for months."],
["absence","n","Abwesenheit, Fehlen","In the absence of evidence, the case collapsed."],
["absurd","adj","absurd, widersinnig","It seems absurd to pay twice for the same service."],
["abuse","n,v","Missbrauch, missbrauchen","He was accused of abusing his position."],
["academy","n","Akademie","She trained at the national academy of music."],
["accelerate","v","beschleunigen","Rising costs accelerated the decline of the industry."],
["acceptance","n","Annahme, Akzeptanz","The idea has gained wide acceptance among engineers."],
["accessible","adj","zugänglich, erreichbar","The archive is now accessible to the public."],
["accomplishment","n","Leistung, Errungenschaft","Finishing the tunnel on time was a real accomplishment."],
["accordingly","adv","entsprechend, dementsprechend","Costs have risen and prices were adjusted accordingly."],
["accountability","n","Rechenschaftspflicht","Voters demanded greater accountability from the ministry."],
["accountable","adj","rechenschaftspflichtig","Managers are accountable for the safety of the site."],
["accumulate","v","ansammeln, anhäufen","Dust had accumulated on the machines over the winter."],
["accumulation","n","Ansammlung, Anhäufung","The accumulation of debt worried the investors."],
["accusation","n","Anschuldigung, Vorwurf","He rejected the accusation of fraud."],
["accused","n","der Angeklagte","The accused refused to answer any questions."],
["acid","n","Säure","The acid slowly damaged the concrete surface."],
["acquisition","n","Erwerb, Übernahme","The acquisition of the smaller firm cost millions."],
["activation","n","Aktivierung","Activation of the alarm requires a code."],
["activist","n","Aktivist","Activists gathered outside the town hall."],
["acute","adj","akut, heftig","There is an acute shortage of skilled workers."],
["adaptation","n","Anpassung, Bearbeitung","Adaptation to the new rules took several months."],
["adhere","v","sich halten an, haften","All firms must adhere to the safety standards."],
["adjacent","adj","angrenzend, benachbart","The office is adjacent to the main hall."],
["adjustment","n","Anpassung, Justierung","A small adjustment to the design solved the problem."],
["administer","v","verwalten, verabreichen","The fund is administered by an independent board."],
["administrative","adj","administrativ, Verwaltungs-","Most of his time goes on administrative work."],
["administrator","n","Verwalter, Administrator","The administrator handles all student records."],
["admission","n","Eintritt, Zugeständnis","His silence was taken as an admission of guilt."],
["adolescent","n,adj","Jugendlicher, jugendlich","The study followed adolescents over five years."],
["adoption","n","Adoption, Übernahme","The adoption of the new standard was slow."],
["adverse","adj","nachteilig, ungünstig","Work stopped because of adverse weather conditions."],
["advocate","n,v","Befürworter, befürworten","She advocates a shorter working week."],
["aesthetic","adj","ästhetisch","The bridge was chosen for aesthetic reasons."],
["affection","n","Zuneigung","He spoke about his old school with real affection."],
["aftermath","n","Nachwirkungen, Folgezeit","In the aftermath of the storm, roads stayed closed."],
["aggression","n","Aggression","The report warned against military aggression."],
["agricultural","adj","landwirtschaftlich","Agricultural land is disappearing near the city."],
["aide","n","Assistent, Berater","A senior aide confirmed the meeting."],
["alert","v,n,adj","alarmieren, Warnung, wachsam","Staff alerted the fire brigade immediately."],
["align","v","ausrichten, angleichen","We need to align the schedule with the budget."],
["alignment","n","Ausrichtung, Angleichung","The alignment of the road follows the valley."],
["alike","adj,adv","ähnlich, gleichermaßen","The plan was criticised by students and staff alike."],
["allegation","n","Behauptung, Vorwurf","The company denied all allegations of corruption."],
["allege","v","behaupten","He is alleged to have taken money from the fund."],
["allegedly","adv","angeblich","The documents were allegedly destroyed."],
["alliance","n","Bündnis, Allianz","The two parties formed an unlikely alliance."],
["allocate","v","zuteilen, zuweisen","More money was allocated to public transport."],
["allocation","n","Zuteilung, Verteilung","The allocation of funds caused a long debate."],
["allowance","n","Zuschuss, Freibetrag","Employees receive a travel allowance each month."],
["ally","n","Verbündeter","The minister found an ally in the finance committee."],
["aluminium","n","Aluminium","The frame is made of lightweight aluminium."],
["amateur","n,adj","Amateur, laienhaft","The photographs were clearly the work of an amateur."],
["ambassador","n","Botschafter","The ambassador was called back to the capital."],
["amend","v","ändern, abändern","The contract was amended after long negotiations."],
["amendment","n","Änderung, Zusatzartikel","The amendment was passed by a narrow margin."],
["amid","prep","inmitten, mitten in","The plan was dropped amid growing criticism."],
["analogy","n","Analogie, Vergleich","He drew an analogy between the brain and a computer."],
["anchor","n","Anker","The ship dropped anchor outside the harbour."],
["anonymous","adj","anonym","The tip came from an anonymous caller."],
["apparel","n","Bekleidung","The company sells sports apparel worldwide."],
["appealing","adj","ansprechend, reizvoll","The offer sounded appealing at first."],
["appetite","n","Appetit, Verlangen","There is little appetite for another reform."],
["applaud","v","applaudieren, loben","Critics applauded the decision to reopen the museum."],
["applicable","adj","anwendbar, zutreffend","These rules are applicable to all new buildings."],
["appoint","v","ernennen, bestellen","She was appointed head of the department."],
["appreciation","n","Wertschätzung, Wertsteigerung","He showed his appreciation with a short speech."],
["arbitrary","adj","willkürlich","The choice of date seemed completely arbitrary."],
["architectural","adj","architektonisch","The city is famous for its architectural heritage."],
["archive","n","Archiv","The letters are kept in the national archive."],
["arena","n","Arena, Schauplatz","He entered the political arena at thirty."],
["arm","v","bewaffnen","The group was armed by a foreign government."],
["array","n","Reihe, Aufgebot","The shop offers an impressive array of tools."],
["articulate","v","deutlich ausdrücken","She articulated her concerns very clearly."],
["ash","n","Asche","A layer of ash covered the whole village."],
["aspiration","n","Bestreben, Ambition","His aspirations went far beyond a local job."],
["aspire","v","anstreben, streben nach","Many students aspire to work abroad."],
["assassination","n","Attentat, Ermordung","The assassination shocked the entire country."],
["assault","n,v","Angriff, angreifen","He was charged with assault after the incident."],
["assemble","v","versammeln, zusammenbauen","The parts are assembled in a local factory."],
["assembly","n","Versammlung, Montage","The assembly voted against the proposal."],
["assert","v","behaupten, geltend machen","She asserted that the data had been misread."],
["assertion","n","Behauptung","His assertion was not supported by any evidence."],
["assurance","n","Zusicherung, Gewissheit","We were given an assurance that work would continue."],
["asylum","n","Asyl","The family applied for asylum last year."],
["atrocity","n","Gräueltat","The court examined atrocities committed during the war."],
["attain","v","erreichen, erlangen","Few students attain that level of fluency."],
["attendance","n","Teilnahme, Besucherzahl","Attendance at the lectures has fallen sharply."],
["attribute","n,v","Merkmal, zuschreiben","She attributes her success to hard work."],
["auction","n","Auktion, Versteigerung","The painting was sold at auction for a record price."],
["audit","n,v","Prüfung, prüfen","An external firm audits the accounts every year."],
["authentic","adj","authentisch, echt","The document was proved to be authentic."],
["authorise","v","genehmigen, bevollmächtigen","Only the director can authorise such payments."],
["auto","n","Auto","The auto industry faces a difficult year."],
["autonomy","n","Autonomie, Eigenständigkeit","The region was given greater autonomy."],
["availability","n","Verfügbarkeit","The availability of materials delayed the project."],
["await","v","erwarten, entgegensehen","We await the results of the investigation."]
],
"B":[
["backdrop","n","Hintergrund, Kulisse","The talks took place against a backdrop of protests."],
["backing","n","Unterstützung, Rückhalt","The plan has the backing of several investors."],
["backup","n","Sicherung, Ersatz","Always keep a backup of your files."],
["bail","n","Kaution","He was released on bail until the trial."],
["ballot","n","Stimmzettel, Wahlgang","Members will decide the issue by secret ballot."],
["bankruptcy","n","Insolvenz, Bankrott","The firm filed for bankruptcy in March."],
["banner","n","Banner, Transparent","Protesters carried banners through the city centre."],
["bare","adj","nackt, bloß","The walls of the flat were completely bare."],
["barrel","n","Fass, Lauf","Oil prices fell below sixty dollars a barrel."],
["battlefield","n","Schlachtfeld","The old battlefield is now a quiet meadow."],
["bay","n","Bucht","Small boats were anchored in the bay."],
["beam","n","Balken, Strahl","A steel beam supports the whole roof."],
["beast","n","Bestie, Tier","The story describes a beast living in the forest."],
["behalf","n","Namen (on behalf of: im Namen von)","She accepted the award on behalf of the team."],
["behavioural","adj","verhaltensbezogen","The study looks at behavioural changes in children."],
["beloved","adj","geliebt","He returned to his beloved home town."],
["bench","n","Bank","They sat on a bench facing the river."],
["benchmark","n","Maßstab, Vergleichswert","The report sets a benchmark for future projects."],
["beneath","prep","unter, unterhalb","A cable runs beneath the road."],
["beneficiary","n","Begünstigter, Nutznießer","Small firms were the main beneficiaries of the reform."],
["betray","v","verraten","He felt betrayed by his closest colleagues."],
["betrayal","n","Verrat","The decision was seen as a betrayal of voters."],
["beverage","n","Getränk","No hot beverages are allowed in the library."],
["bind","v","binden, verpflichten","The agreement binds both sides for ten years."],
["biography","n","Biografie","Her biography of the architect took six years."],
["bishop","n","Bischof","The bishop spoke at the memorial service."],
["bizarre","adj","bizarr, seltsam","The whole situation felt strangely bizarre."],
["blade","n","Klinge, Blatt","One blade of the turbine had to be replaced."],
["blast","n,v","Explosion, sprengen","The blast damaged several nearby buildings."],
["bleed","v","bluten","The wound was still bleeding after an hour."],
["blend","n,v","Mischung, mischen","The design blends old and new elements."],
["bless","v","segnen","The new bridge was blessed by the local priest."],
["blessing","n","Segen","The change proved to be a mixed blessing."],
["boast","v","prahlen, sich rühmen","The town boasts one of the oldest markets in Europe."],
["bonus","n","Bonus, Prämie","Staff received a bonus at the end of the year."],
["boom","n","Aufschwung, Boom","The construction boom lasted almost a decade."],
["bounce","v","springen, abprallen","The ball bounced twice before he caught it."],
["boundary","n","Grenze","The river forms the boundary between the two regions."],
["bow","v","sich verbeugen","The performers bowed to a long applause."],
["breach","n,v","Verstoß, verletzen","The company was fined for a breach of contract."],
["breakdown","n","Panne, Zusammenbruch, Aufschlüsselung","He gave us a full breakdown of the costs."],
["breakthrough","n","Durchbruch","The team announced a breakthrough in battery research."],
["breed","v","züchten, sich vermehren","These birds breed on the northern coast."],
["broadband","n","Breitband","Broadband access is still poor in rural areas."],
["browser","n","Browser","The site does not work in older browsers."],
["brutal","adj","brutal","The report describes brutal working conditions."],
["buffer","n","Puffer","The reserve acts as a buffer against rising prices."],
["bulk","n","Großteil, Masse","The bulk of the money went into the new building."],
["burden","n","Last, Bürde","The tax places a heavy burden on small firms."],
["bureaucracy","n","Bürokratie","Endless bureaucracy delayed the permit for months."],
["burial","n","Beerdigung, Bestattung","The burial took place in his home village."]
],
"C":[
["cabinet","n","Kabinett, Schrank","The cabinet met to discuss the energy crisis."],
["calculation","n","Berechnung","A single calculation error delayed the whole design."],
["canvas","n","Leinwand","The artist stretched a new canvas over the frame."],
["capability","n","Fähigkeit, Leistungsvermögen","The firm lacks the capability to build such a bridge."],
["capitalism","n","Kapitalismus","The book offers a sharp critique of modern capitalism."],
["capitalist","n,adj","Kapitalist, kapitalistisch","They compared two very different capitalist systems."],
["cargo","n","Fracht, Ladung","The ship carried a cargo of steel and timber."],
["carriage","n","Waggon, Kutsche","The front carriage of the train was almost empty."],
["carve","v","schnitzen, einritzen","Their names were carved into the stone."],
["casualty","n","Opfer, Verletzter","There were no casualties in the accident."],
["catalogue","n","Katalog","The full catalogue is available online."],
["cater","v","versorgen, eingehen auf","The course caters for students with no prior knowledge."],
["cattle","n","Rinder, Vieh","Cattle were grazing on the hillside."],
["caution","n","Vorsicht","He approached the topic with great caution."],
["cautious","adj","vorsichtig","Investors remain cautious about the housing market."],
["cease","v","aufhören, einstellen","Production ceased at the end of the year."],
["cemetery","n","Friedhof","The old cemetery lies just outside the village."],
["chamber","n","Kammer","The upper chamber rejected the proposal."],
["chaos","n","Chaos","The strike caused chaos at the airport."],
["characterise","v","kennzeichnen, charakterisieren","The period was characterised by rapid growth."],
["charm","n","Charme, Reiz","The old town has a certain charm."],
["charter","n","Charta, Urkunde","The city charter dates back to the fourteenth century."],
["choir","n","Chor","She has sung in the church choir for years."],
["chronic","adj","chronisch","The region suffers from a chronic water shortage."],
["chunk","n","Brocken, großes Stück","A large chunk of the budget went on materials."],
["circulate","v","zirkulieren, in Umlauf bringen","Rumours circulated for weeks before the announcement."],
["circulation","n","Umlauf, Auflage","The newspaper has a circulation of half a million."],
["citizenship","n","Staatsbürgerschaft","He applied for citizenship after ten years."],
["civic","adj","bürgerlich, städtisch","Voting is a basic civic duty."],
["civilian","n","Zivilist","Aid workers helped civilians leave the area."],
["clarity","n","Klarheit","The report lacks clarity on several points."],
["clash","n,v","Zusammenstoß, aufeinanderprallen","The two ministers clashed over the budget."],
["classification","n","Einteilung, Klassifizierung","The classification of soil types follows a standard."],
["cling","v","sich klammern, festhalten","He still clings to the idea of a quick solution."],
["clinical","adj","klinisch","Clinical trials will start next spring."],
["closure","n","Schließung, Abschluss","The closure of the plant cost two hundred jobs."],
["cluster","n","Ansammlung, Cluster","A cluster of small firms grew around the university."],
["coalition","n","Koalition","The coalition collapsed after only a year."],
["coastal","adj","Küsten-","Coastal towns are most at risk from flooding."],
["cocktail","n","Cocktail","They served cocktails on the terrace."],
["cognitive","adj","kognitiv","Sleep has a strong effect on cognitive performance."],
["coincide","v","zusammenfallen, übereinstimmen","The conference coincides with the exam period."],
["collaborate","v","zusammenarbeiten","Two universities collaborated on the study."],
["collaboration","n","Zusammenarbeit","The bridge was built in collaboration with a Swiss firm."],
["collective","adj","kollektiv, gemeinsam","The decision was a collective one."],
["collision","n","Zusammenstoß, Kollision","The collision damaged both vehicles badly."],
["colonial","adj","kolonial","Many streets still carry colonial names."],
["columnist","n","Kolumnist","A well known columnist attacked the plan."],
["combat","n,v","Kampf, bekämpfen","New measures aim to combat tax evasion."],
["commence","v","beginnen","Work on the tunnel will commence in April."],
["commentary","n","Kommentar","His commentary on the crisis was widely read."],
["commentator","n","Kommentator","Several commentators predicted the outcome."],
["commerce","n","Handel","The river was once vital for commerce."],
["commissioner","n","Kommissar, Beauftragter","The commissioner announced a full inquiry."],
["commodity","n","Ware, Rohstoff","Clean water is becoming a valuable commodity."],
["communist","n,adj","Kommunist, kommunistisch","The building dates from the communist era."],
["companion","n","Begleiter, Gefährte","The dog was his constant companion."],
["comparable","adj","vergleichbar","The two projects are not really comparable."],
["compassion","n","Mitgefühl","She spoke about the refugees with real compassion."],
["compel","v","zwingen, nötigen","Rising costs compelled them to change the design."],
["compelling","adj","überzeugend, zwingend","He made a compelling case for more funding."],
["compensate","v","entschädigen, ausgleichen","Residents were compensated for the noise."],
["compensation","n","Entschädigung, Ausgleich","They received compensation for the delay."],
["competence","n","Kompetenz, Fachkenntnis","Nobody doubted his technical competence."],
["competent","adj","kompetent, fähig","She is a highly competent engineer."],
["compile","v","zusammenstellen, erstellen","The team compiled a list of all defects."],
["complement","n,v","Ergänzung, ergänzen","The new wing complements the older building."],
["complexity","n","Komplexität","The complexity of the system surprised everyone."],
["compliance","n","Einhaltung, Befolgung","Compliance with the safety rules is checked monthly."],
["complication","n","Komplikation, Erschwernis","An unexpected complication delayed the handover."],
["comply","v","sich fügen, einhalten","All buildings must comply with the fire code."],
["composition","n","Zusammensetzung, Komposition","The composition of the concrete was altered."],
["comprise","v","umfassen, bestehen aus","The course comprises six modules."],
["compromise","n,v","Kompromiss, gefährden","After long talks they reached a compromise."],
["compute","v","berechnen","The model computes the load in a few seconds."],
["conceal","v","verbergen, verheimlichen","The damage had been concealed behind a wall."],
["concede","v","zugeben, einräumen","He conceded that the schedule was too tight."],
["conceive","v","sich vorstellen, ersinnen","The plan was conceived over twenty years ago."],
["conception","n","Vorstellung, Auffassung","Their conception of justice differs from ours."],
["concession","n","Zugeständnis, Konzession","The union won several important concessions."],
["condemn","v","verurteilen","Both sides condemned the attack."],
["confer","v","verleihen, beraten","The degree confers no special rights."],
["confession","n","Geständnis, Beichte","His confession came after hours of questioning."],
["configuration","n","Konfiguration, Anordnung","A different configuration would save space."],
["confine","v","beschränken, einsperren","Please confine your remarks to the main topic."],
["confirmation","n","Bestätigung","We are still waiting for written confirmation."],
["confront","v","konfrontieren, gegenübertreten","The government must confront the housing shortage."],
["confrontation","n","Konfrontation","A direct confrontation was avoided."],
["congratulate","v","gratulieren","She congratulated him on his promotion."],
["congregation","n","Gemeinde","The congregation filled the small church."],
["congressional","adj","den Kongress betreffend","A congressional committee examined the case."],
["conquer","v","erobern, bezwingen","The region was conquered in the twelfth century."],
["conscience","n","Gewissen","He acted purely out of conscience."],
["consciously","adv","bewusst","She consciously avoided the subject."],
["consciousness","n","Bewusstsein","The patient regained consciousness after an hour."],
["consecutive","adj","aufeinanderfolgend","It rained for five consecutive days."],
["consensus","n","Konsens","There is no consensus among the experts."],
["consent","n,v","Zustimmung, zustimmen","The work needs the written consent of the owner."],
["conserve","v","bewahren, schonen","New windows help conserve energy."],
["consistency","n","Beständigkeit, Konsistenz","The team has played with real consistency."],
["consolidate","v","festigen, zusammenlegen","They consolidated their debts into a single loan."],
["consolidation","n","Festigung, Zusammenlegung","Consolidation of the two departments saved money."],
["constitute","v","darstellen, bilden","Such behaviour constitutes a breach of contract."],
["constitution","n","Verfassung","The constitution guarantees freedom of the press."],
["constitutional","adj","verfassungsmäßig","The court found the law constitutional."],
["constraint","n","Zwang, Einschränkung","Time constraints forced a simpler solution."],
["consultation","n","Beratung, Anhörung","The plan was changed after public consultation."],
["contemplate","v","erwägen, betrachten","They are contemplating a move to a larger office."],
["contempt","n","Verachtung","He spoke of the rules with open contempt."],
["contend","v","behaupten, ringen","Critics contend that the data is unreliable."],
["contender","n","Anwärter, Konkurrent","She is a serious contender for the post."],
["content","adj","zufrieden","He seemed content with the outcome."],
["contention","n","Behauptung, Streitpunkt","The route remains a point of contention."],
["continually","adv","fortwährend, ständig","The design was continually revised."],
["contractor","n","Auftragnehmer, Bauunternehmer","The contractor missed several deadlines."],
["contradiction","n","Widerspruch","There is a clear contradiction in his statement."],
["contrary","adj,n","gegenteilig, Gegenteil","Contrary to expectations, costs actually fell."],
["contributor","n","Beitragender, Mitwirkender","Traffic is the main contributor to local pollution."],
["conversion","n","Umwandlung, Umbau","The conversion of the warehouse took two years."],
["convict","n,v","Sträfling, verurteilen","He was convicted of fraud last year."],
["conviction","n","Überzeugung, Verurteilung","She argued her case with great conviction."],
["cooperate","v","zusammenarbeiten","Both firms agreed to cooperate on the design."],
["cooperative","adj","kooperativ","The staff were friendly and cooperative."],
["coordinate","v","koordinieren","She coordinates the work of four teams."],
["coordination","n","Koordination","Better coordination would have avoided the delay."],
["coordinator","n","Koordinator","The project coordinator reports every Friday."],
["copyright","n","Urheberrecht","The images are protected by copyright."],
["correction","n","Korrektur","A small correction was added to the report."],
["correlate","v","in Zusammenhang stehen","Income correlates strongly with education."],
["correlation","n","Zusammenhang, Korrelation","The study found no correlation between the two."],
["correspond","v","entsprechen, korrespondieren","The drawings do not correspond to the site."],
["correspondence","n","Briefwechsel, Übereinstimmung","All correspondence is kept for ten years."],
["correspondent","n","Korrespondent","Their correspondent in Cairo filed the report."],
["corresponding","adj","entsprechend","Sales rose by ten percent on the corresponding month."],
["correspondingly","adv","entsprechend","Demand fell and prices dropped correspondingly."],
["corrupt","adj","korrupt","Several corrupt officials were removed."],
["corruption","n","Korruption","Corruption slowed every stage of the project."],
["costly","adj","kostspielig","Repairing the roof proved extremely costly."],
["councillor","n","Ratsmitglied","A local councillor raised the issue."],
["counselling","n","Beratung","The university offers free counselling for students."],
["counsellor","n","Berater","A counsellor was available after the accident."],
["counter","v","entgegnen, entgegenwirken","He countered the criticism with fresh figures."],
["counterpart","n","Gegenstück, Amtskollege","She met her French counterpart in Berlin."],
["countless","adj","zahllos","Countless small changes improved the design."],
["coup","n","Staatsstreich, Coup","The government was removed in a military coup."],
["courtesy","n","Höflichkeit","He replied with unusual courtesy."],
["craft","n,v","Handwerk, kunstvoll fertigen","The speech was carefully crafted."],
["crawl","v","kriechen, krabbeln","Traffic crawled through the city centre."],
["creator","n","Schöpfer, Urheber","The creator of the series lives in Vienna."],
["credibility","n","Glaubwürdigkeit","The scandal damaged his credibility."],
["credible","adj","glaubwürdig","There is no credible evidence for that claim."],
["creep","v","schleichen, kriechen","Doubts began to creep into his mind."],
["criterion","n","Kriterium","Cost was not the only criterion."],
["critique","n","Kritik, kritische Analyse","The book is a critique of modern planning."],
["crown","n","Krone","The crown was kept in a locked case."],
["crude","adj","grob, roh","It was a crude but effective solution."],
["crush","v","zerdrücken, niederschlagen","The protest was quickly crushed."],
["crystal","n","Kristall","Salt crystals formed on the surface."],
["cult","n","Kult, Sekte","The film has become a cult favourite."],
["cultivate","v","anbauen, pflegen","He carefully cultivated contacts in the ministry."],
["curiosity","n","Neugier","Curiosity drove her to open the file."],
["custody","n","Gewahrsam, Sorgerecht","The suspect remains in police custody."],
["cutting","n,adj","Ausschnitt, schneidend","He kept a cutting from the local paper."],
["cynical","adj","zynisch","He took a cynical view of the whole reform."]
],
"D":[
["dam","n","Damm, Staumauer","The dam supplies power to the whole valley."],
["damaging","adj","schädlich","The report was damaging to his reputation."],
["dawn","n","Morgengrauen, Beginn","They set off at dawn."],
["debris","n","Trümmer, Schutt","Debris blocked the road for two days."],
["debut","n","Debüt","She made her debut at the age of nineteen."],
["decision-making","n","Entscheidungsfindung","Staff want a bigger role in decision-making."],
["decisive","adj","entscheidend, entschlossen","His support proved decisive."],
["declaration","n","Erklärung, Deklaration","The declaration was signed by twelve countries."],
["dedicated","adj","engagiert, eigens bestimmt","A dedicated team handles all complaints."],
["dedication","n","Hingabe, Widmung","Her dedication to the project was obvious."],
["deed","n","Tat, Urkunde","He was judged by his deeds, not his words."],
["deem","v","erachten, halten für","The building was deemed unsafe."],
["default","n","Standardeinstellung, Zahlungsausfall","The default setting works for most users."],
["defect","n","Mangel, Defekt","A design defect caused the cracks."],
["defensive","adj","defensiv, abwehrend","He became defensive when questioned."],
["deficiency","n","Mangel, Defizit","The report lists several deficiencies in the design."],
["deficit","n","Defizit","The city is trying to reduce its deficit."],
["definitive","adj","endgültig, maßgeblich","There is still no definitive answer."],
["defy","v","trotzen, sich widersetzen","The results defy all expectations."],
["delegate","n","Delegierter","Delegates voted on the proposal."],
["delegation","n","Delegation, Übertragung","A delegation travelled to Brussels."],
["delicate","adj","heikel, empfindlich","This is a delicate political question."],
["demon","n","Dämon","He wrote about his own demons."],
["denial","n","Leugnung, Ablehnung","His denial convinced nobody."],
["denounce","v","anprangern, verurteilen","Several groups denounced the decision."],
["dense","adj","dicht","The area is covered by dense forest."],
["density","n","Dichte","Population density is highest near the river."],
["dependence","n","Abhängigkeit","The country wants to cut its dependence on imports."],
["depict","v","darstellen, schildern","The film depicts life in a small town."],
["deploy","v","einsetzen, stationieren","New sensors were deployed along the line."],
["deployment","n","Einsatz, Stationierung","The deployment of troops was widely criticised."],
["deprive","v","berauben, vorenthalten","Many families were deprived of clean water."],
["deputy","n","Stellvertreter","The deputy took over during his absence."],
["descend","v","hinabsteigen, abstammen","The path descends steeply into the valley."],
["descent","n","Abstieg, Abstammung","She is of Polish descent."],
["designate","v","bestimmen, ausweisen","The area was designated a nature reserve."],
["desirable","adj","wünschenswert, begehrt","A second exit would be highly desirable."],
["destructive","adj","zerstörerisch","His criticism was purely destructive."],
["detain","v","festhalten, in Gewahrsam nehmen","Two men were detained at the border."],
["detection","n","Erkennung, Aufspürung","Early detection saves lives."],
["detention","n","Haft, Nachsitzen","He spent three weeks in detention."],
["deteriorate","v","sich verschlechtern","The condition of the bridge deteriorated quickly."],
["devastate","v","verwüsten, erschüttern","The flood devastated the lower town."],
["devise","v","ersinnen, entwickeln","They devised a cheaper method."],
["diagnose","v","diagnostizieren","The fault was diagnosed within an hour."],
["diagnosis","n","Diagnose","A second diagnosis confirmed the first."],
["dictate","v","diktieren, vorschreiben","Costs dictated the choice of material."],
["dictator","n","Diktator","The dictator ruled for thirty years."],
["differentiate","v","unterscheiden","It is hard to differentiate between the two models."],
["dignity","n","Würde","He lost his job but kept his dignity."],
["dilemma","n","Dilemma, Zwickmühle","The council faces a real dilemma."],
["dimension","n","Dimension, Ausmaß","The crisis has an international dimension."],
["diminish","v","verringern, abnehmen","Interest in the topic has diminished."],
["dip","v","eintauchen, kurz sinken","Sales dipped slightly in the summer."],
["diplomat","n","Diplomat","A senior diplomat was sent to the talks."],
["diplomatic","adj","diplomatisch","She gave a very diplomatic answer."],
["directory","n","Verzeichnis","Their address is in the online directory."],
["disastrous","adj","katastrophal","The decision proved disastrous."],
["discard","v","wegwerfen, verwerfen","The first design was quickly discarded."],
["discharge","v","entlassen, ableiten","Waste water is discharged into the river."],
["disclose","v","offenlegen, enthüllen","The bank refused to disclose the figures."],
["disclosure","n","Offenlegung, Enthüllung","The disclosure caused a public outcry."],
["discourse","n","Diskurs, Rede","The book studies political discourse."],
["discretion","n","Ermessen, Diskretion","The decision is left to the manager's discretion."],
["discrimination","n","Diskriminierung","The law bans discrimination at work."],
["disregard","v","missachten, ignorieren","He disregarded every warning."],
["dismissal","n","Entlassung, Abweisung","She challenged her dismissal in court."],
["displace","v","verdrängen, vertreiben","Thousands were displaced by the flood."],
["disposal","n","Entsorgung, Verfügung","Waste disposal costs have doubled."],
["dispose of","v","entsorgen, loswerden","Old batteries must be disposed of properly."],
["dispute","n,v","Streit, bestreiten","The two firms are in a legal dispute."],
["disrupt","v","stören, unterbrechen","Roadworks disrupted traffic all week."],
["disruption","n","Störung, Unterbrechung","Passengers face major disruption tomorrow."],
["dissolve","v","auflösen","The salt dissolves quickly in warm water."],
["distinction","n","Unterscheidung, Auszeichnung","He draws a clear distinction between the two."],
["distinctive","adj","unverwechselbar, markant","The tower has a distinctive shape."],
["distort","v","verzerren, entstellen","The headline distorted what she actually said."],
["distress","n","Not, Bedrängnis","The ship sent a distress signal."],
["disturbing","adj","beunruhigend","The report makes disturbing reading."],
["divert","v","umleiten, ablenken","Traffic was diverted around the site."],
["divine","adj","göttlich","They believed in a divine plan."],
["doctrine","n","Doktrin, Lehre","The doctrine has shaped policy for decades."],
["documentation","n","Dokumentation, Unterlagen","All documentation must be submitted by Friday."],
["domain","n","Bereich, Domäne","This lies outside my domain."],
["dominance","n","Vorherrschaft, Dominanz","The firm lost its dominance in the market."],
["donor","n","Spender","A private donor funded the new wing."],
["dose","n","Dosis","He took a double dose by mistake."],
["drawback","n","Nachteil","The main drawback is the price."],
["drain","v","entwässern, abfließen lassen","The field was drained before building started."],
["drift","v","treiben, abdriften","The talks drifted away from the main issue."],
["drown","v","ertrinken, ertränken","Two people drowned in the flood."],
["dual","adj","doppelt, zweifach","He holds dual citizenship."],
["dub","v","nennen, synchronisieren","The plan was quickly dubbed a failure."],
["dumb","adj","stumm, dumm","He was struck dumb by the news."],
["duo","n","Duo","The duo has played together for years."]
],
"E":[
["earnings","n","Einnahmen, Verdienst","Company earnings rose by twelve percent."],
["ease","n,v","Leichtigkeit, erleichtern","She solved the problem with ease."],
["echo","n,v","Echo, widerhallen","His words echoed the concerns of many staff."],
["ecological","adj","ökologisch","The dam had serious ecological effects."],
["educator","n","Pädagoge, Erzieher","Educators welcomed the new curriculum."],
["effectiveness","n","Wirksamkeit","Nobody has tested the effectiveness of the method."],
["efficiency","n","Effizienz, Wirtschaftlichkeit","Energy efficiency was the main goal."],
["ego","n","Ego, Selbstbewusstsein","His ego made cooperation difficult."],
["elaborate","adj","aufwendig, ausgeklügelt","They built an elaborate drainage system."],
["electoral","adj","Wahl-, wahlbezogen","The electoral system was reformed in 2005."],
["elevate","v","erhöhen, anheben","The role was elevated to board level."],
["eligible","adj","berechtigt, anspruchsberechtigt","Only residents are eligible for the grant."],
["elite","n","Elite","A small elite controls most of the land."],
["embark","v","aufbrechen, beginnen","They embarked on a five year programme."],
["embarrassment","n","Verlegenheit, Peinlichkeit","The error caused real embarrassment."],
["embassy","n","Botschaft","She works at the German embassy."],
["embed","v","einbetten, verankern","The sensors are embedded in the concrete."],
["embody","v","verkörpern","The building embodies the ideas of its architect."],
["emergence","n","Aufkommen, Entstehung","The emergence of new materials changed the field."],
["empirical","adj","empirisch","There is little empirical support for the claim."],
["empower","v","befähigen, ermächtigen","The law empowers councils to act faster."],
["enact","v","erlassen, in Kraft setzen","The rules were enacted last summer."],
["encompass","v","umfassen, einschließen","The study encompasses twelve countries."],
["encouragement","n","Ermutigung","A word of encouragement helped him continue."],
["encouraging","adj","ermutigend","The first results are encouraging."],
["endeavour","n","Bestreben, Bemühen","The rescue was a joint endeavour."],
["endless","adj","endlos","There were endless delays at the border."],
["endorse","v","befürworten, unterstützen","Two unions endorsed the proposal."],
["endorsement","n","Befürwortung, Billigung","The plan won the endorsement of the mayor."],
["endure","v","ertragen, überdauern","The bridge has endured two centuries of traffic."],
["enforce","v","durchsetzen","The speed limit is rarely enforced."],
["enforcement","n","Durchsetzung, Vollzug","Enforcement of the rules varies by region."],
["engagement","n","Engagement, Verpflichtung","Public engagement improved the final design."],
["engaging","adj","ansprechend, fesselnd","She gave an engaging talk on soil mechanics."],
["enrich","v","bereichern","Travel enriched his understanding of the trade."],
["enrol","v","einschreiben, anmelden","Over four hundred students enrolled this year."],
["enterprise","n","Unternehmen, Vorhaben","The whole enterprise proved far too costly."],
["enthusiast","n","Enthusiast, Liebhaber","The museum attracts railway enthusiasts."],
["entitle","v","berechtigen, betiteln","The card entitles you to a discount."],
["entity","n","Einheit, Rechtsträger","The subsidiary is a separate legal entity."],
["epidemic","n","Epidemie","The epidemic spread through three regions."],
["equality","n","Gleichheit","The party campaigns for greater equality."],
["equation","n","Gleichung","Cost is only one part of the equation."],
["erect","v","errichten, aufstellen","A temporary shelter was erected overnight."],
["escalate","v","eskalieren, verschärfen","The dispute escalated into a strike."],
["escort","n,v","Begleitung, begleiten","Police escorted the convoy through the town."],
["essence","n","Wesen, Kern","In essence, the two plans are identical."],
["establishment","n","Einrichtung, Establishment","He rebelled against the political establishment."],
["eternal","adj","ewig","She had an eternal optimism about the project."],
["evacuate","v","evakuieren, räumen","Residents were evacuated within an hour."],
["evoke","v","hervorrufen, wachrufen","The photographs evoke a lost world."],
["evolutionary","adj","evolutionär","The change was evolutionary, not sudden."],
["exaggerate","v","übertreiben","The press exaggerated the scale of the damage."],
["excellence","n","Vortrefflichkeit, Exzellenz","The institute is a centre of excellence."],
["exceptional","adj","außergewöhnlich","The results were exceptional by any standard."],
["excess","n","Überschuss, Übermaß","Excess water is pumped into the canal."],
["exclusion","n","Ausschluss","The exclusion of small firms was criticised."],
["exclusive","adj","exklusiv, ausschließlich","The club has an exclusive membership."],
["exclusively","adv","ausschließlich","The lane is used exclusively by buses."],
["execute","v","ausführen, vollstrecken","The plan was executed with great precision."],
["execution","n","Ausführung, Hinrichtung","Poor execution ruined a good idea."],
["exert","v","ausüben, aufwenden","The beam exerts pressure on the wall."],
["exile","n","Exil, Verbannung","He spent twenty years in exile."],
["expenditure","n","Ausgaben, Aufwand","Public expenditure on roads has fallen."],
["experimental","adj","experimentell, versuchsweise","The material is still at an experimental stage."],
["expire","v","ablaufen, verfallen","The permit expires at the end of March."],
["explicit","adj","ausdrücklich, eindeutig","The contract contains an explicit warranty."],
["explicitly","adv","ausdrücklich","The report explicitly rejects that option."],
["exploitation","n","Ausbeutung, Nutzung","The exploitation of workers was widely reported."],
["explosive","n,adj","Sprengstoff, explosiv","The situation became politically explosive."],
["extremist","n","Extremist","A small group of extremists disrupted the meeting."]
],
"F":[
["facilitate","v","erleichtern, ermöglichen","The software facilitates data exchange between teams."],
["faction","n","Fraktion, Gruppierung","A small faction opposed the merger."],
["fade","v","verblassen, schwinden","Interest in the scheme soon faded."],
["fairness","n","Fairness, Gerechtigkeit","Everyone praised the fairness of the process."],
["fatal","adj","tödlich, verhängnisvoll","A fatal error in the calculation was found."],
["fate","n","Schicksal","The fate of the old mill is still unclear."],
["favourable","adj","günstig, wohlwollend","Conditions were favourable for pouring concrete."],
["feat","n","Leistung, Meisterstück","Building it in nine months was quite a feat."],
["felony","n","Schwerverbrechen","He was convicted of a felony in 2011."],
["feminist","n,adj","Feministin, feministisch","She wrote a feminist history of the trade."],
["fibre","n","Faser","The panels are made of carbon fibre."],
["fierce","adj","heftig, erbittert","There was fierce competition for the contract."],
["filmmaker","n","Filmemacher","A young filmmaker documented the demolition."],
["filter","n,v","Filter, filtern","The system filters out unwanted noise."],
["firearm","n","Schusswaffe","Firearm laws differ widely between states."],
["fiscal","adj","fiskalisch, steuerlich","Fiscal policy tightened after the crisis."],
["flaw","n","Fehler, Makel","The argument has one serious flaw."],
["flawed","adj","fehlerhaft, mangelhaft","The whole study was badly flawed."],
["flee","v","fliehen","Thousands fled the region during the floods."],
["fleet","n","Flotte, Fuhrpark","The company renewed its fleet of trucks."],
["flesh","n","Fleisch","The fruit has soft white flesh."],
["flexibility","n","Flexibilität","The design allows for great flexibility."],
["flourish","v","gedeihen, florieren","Small workshops flourished in the area."],
["fluid","n","Flüssigkeit","Brake fluid was leaking from the pipe."],
["footage","n","Filmmaterial, Aufnahmen","Security footage showed the whole incident."],
["foresee","v","voraussehen","Nobody could foresee the delay."],
["foreigner","n","Ausländer","Foreigners now own most of the flats."],
["forge","v","schmieden, fälschen","They forged a lasting partnership."],
["formula","n","Formel","There is no simple formula for success."],
["formulate","v","formulieren","He formulated the question more carefully."],
["forth","adv","hervor, vorwärts","From that day forth, safety checks were daily."],
["forthcoming","adj","bevorstehend, entgegenkommend","Details of the forthcoming trial were released."],
["foster","v","fördern, begünstigen","The programme fosters links with industry."],
["fragile","adj","zerbrechlich, fragil","The peace remains extremely fragile."],
["franchise","n","Franchise, Wahlrecht","The chain sells franchises across Europe."],
["frankly","adv","offen gesagt","Frankly, the estimate was far too low."],
["fraudulent","adj","betrügerisch","Several fraudulent claims were discovered."],
["frustrating","adj","frustrierend","The permit process was deeply frustrating."],
["frustration","n","Frustration","He could not hide his frustration."],
["functional","adj","funktional, funktionsfähig","The building is plain but highly functional."],
["fundraising","n","Spendensammlung","Fundraising paid for the new roof."]
],
"G":[
["gambling","n","Glücksspiel","Gambling debts ruined the family business."],
["gathering","n","Versammlung, Zusammenkunft","It was a small gathering of former colleagues."],
["gaze","v","starren, blicken","She gazed at the drawings for a long time."],
["gear","n","Ausrüstung, Gang","Bring waterproof gear for the site visit."],
["generic","adj","allgemein, generisch","The answer was too generic to help."],
["genocide","n","Völkermord","The court investigated charges of genocide."],
["glance","v","kurz blicken","He glanced at the schedule and frowned."],
["glimpse","n","flüchtiger Blick","We caught a glimpse of the old tunnel."],
["glorious","adj","glorreich, herrlich","It was a glorious morning on the coast."],
["glory","n","Ruhm, Pracht","The firm never regained its former glory."],
["governance","n","Führung, Unternehmensführung","Poor governance led to the collapse."],
["grace","n","Anmut, Gnade","She accepted the criticism with grace."],
["grasp","v","begreifen, ergreifen","He quickly grasped the essence of the method."],
["grave","adj","ernst, schwerwiegend","The report raises grave concerns."],
["gravity","n","Schwerkraft, Ernst","Nobody understood the gravity of the situation."],
["grid","n","Netz, Raster","The city is built on a strict grid."],
["grief","n","Trauer, Kummer","The village was united in grief."],
["grin","v","grinsen","He grinned when the machine finally started."],
["grind","v","mahlen, zermahlen","The stone was ground into fine powder."],
["grip","n,v","Griff, packen","Fear gripped the whole neighbourhood."],
["gross","adj","brutto, grob","Gross income rose while profits fell."],
["guerrilla","n","Guerillakämpfer","Guerrilla fighters controlled the mountain roads."],
["guidance","n","Anleitung, Beratung","New guidance on fire safety was issued."],
["guilt","n","Schuld","He felt a lasting sense of guilt."],
["gut","n","Darm, Bauchgefühl","His gut told him the figures were wrong."]
],
"H":[
["hail","v","preisen, zujubeln","The design was hailed as a breakthrough."],
["halfway","adv","auf halbem Weg","We stopped halfway up the hill."],
["halt","v","anhalten, stoppen","Work halted when the funding ran out."],
["handful","n","Handvoll","Only a handful of firms submitted a bid."],
["handling","n","Handhabung, Umgang","The handling of the complaint was poor."],
["handy","adj","praktisch, griffbereit","A small torch is always handy on site."],
["harassment","n","Belästigung","The company faced claims of harassment."],
["hardware","n","Hardware, Eisenwaren","The hardware is old but still reliable."],
["harmony","n","Harmonie, Einklang","The extension sits in harmony with the old wing."],
["harsh","adj","hart, rau","Workers face harsh conditions in winter."],
["harvest","n,v","Ernte, ernten","The harvest was poor after the dry summer."],
["hatred","n","Hass","The speech was full of hatred."],
["haunt","v","verfolgen, heimsuchen","That mistake haunted him for years."],
["hazard","n","Gefahr, Risiko","Loose cables are a serious hazard."],
["hence","adv","daher, folglich","Costs rose, hence the change of material."],
["heighten","v","verstärken, erhöhen","The delay heightened public frustration."],
["heritage","n","Erbe, Kulturgut","The town protects its industrial heritage."],
["hierarchy","n","Hierarchie","The firm has a very flat hierarchy."],
["high-profile","adj","hochkarätig, viel beachtet","It was a high-profile case in the national press."],
["homeland","n","Heimat, Heimatland","Many returned to their homeland after the war."],
["hopeful","adj","hoffnungsvoll","Engineers are hopeful about the new method."],
["horizon","n","Horizont","New opportunities appeared on the horizon."],
["hostage","n","Geisel","The hostages were released unharmed."],
["hostile","adj","feindselig, ablehnend","The audience was openly hostile."],
["hostility","n","Feindseligkeit","There was real hostility towards the plan."],
["humanitarian","adj","humanitär","Humanitarian aid reached the region late."],
["humanity","n","Menschheit, Menschlichkeit","He showed great humanity in a hard moment."],
["humble","adj","bescheiden, demütig","Despite his success he remained humble."],
["hydrogen","n","Wasserstoff","Hydrogen may replace gas in heavy industry."],
["hypothesis","n","Hypothese","The data does not support that hypothesis."]
],
"I":[
["identification","n","Identifizierung, Ausweis","Identification of the fault took several days."],
["ideological","adj","ideologisch","The split was ideological rather than personal."],
["ideology","n","Ideologie","Their ideology has changed little since the war."],
["ignorance","n","Unwissenheit","His ignorance of the rules caused the delay."],
["imagery","n","Bildsprache, Bildmaterial","Satellite imagery revealed the damage."],
["immense","adj","gewaltig, immens","The pressure on the team was immense."],
["imminent","adj","unmittelbar bevorstehend","A collapse of the wall seemed imminent."],
["implementation","n","Umsetzung, Einführung","Implementation of the plan starts in June."],
["imprison","v","inhaftieren","He was imprisoned for eight years."],
["inability","n","Unfähigkeit","Her inability to delegate slowed everything down."],
["inadequate","adj","unzureichend","The drainage proved completely inadequate."],
["inappropriate","adj","unangemessen","His comment was clearly inappropriate."],
["incarcerate","v","einsperren, inhaftieren","Hundreds were incarcerated without trial."],
["incarceration","n","Inhaftierung","Long incarceration damaged his health."],
["incidence","n","Häufigkeit, Vorkommen","The incidence of accidents has fallen."],
["inclined","adj","geneigt","I am inclined to accept their offer."],
["inclusion","n","Einbeziehung, Aufnahme","The inclusion of a bike lane was welcomed."],
["incur","v","sich zuziehen, auf sich nehmen","The firm incurred heavy losses last year."],
["indicator","n","Indikator, Anzeiger","Rising rents are a clear indicator of demand."],
["indictment","n","Anklage","The indictment ran to forty pages."],
["indigenous","adj","einheimisch, indigen","Indigenous communities were not consulted."],
["induce","v","herbeiführen, veranlassen","Nothing could induce him to change his mind."],
["indulge","v","frönen, nachgeben","He indulged in a long lunch break."],
["inequality","n","Ungleichheit","Income inequality has grown steadily."],
["infamous","adj","berüchtigt","The junction is infamous for accidents."],
["infect","v","infizieren, anstecken","The whole network was infected within hours."],
["inflict","v","zufügen","The storm inflicted serious damage on the roof."],
["influential","adj","einflussreich","She wrote an influential paper on soil behaviour."],
["infrastructure","n","Infrastruktur","The region needs better transport infrastructure."],
["inherent","adj","innewohnend, inhärent","There is an inherent risk in every tunnel."],
["inhibit","v","hemmen, behindern","High costs inhibit innovation."],
["initiate","v","einleiten, in die Wege leiten","They initiated talks with the landowner."],
["inject","v","einspritzen, zuführen","Fresh capital was injected into the firm."],
["injection","n","Injektion, Zuführung","A cash injection saved the project."],
["injustice","n","Ungerechtigkeit","He spoke out against a clear injustice."],
["inmate","n","Insasse, Häftling","The prison holds six hundred inmates."],
["inquire","v","sich erkundigen, nachfragen","She inquired about the delivery date."],
["insertion","n","Einfügung, Einsetzen","The insertion of a steel plate solved it."],
["insider","n","Insider, Eingeweihter","An insider leaked the figures to the press."],
["inspect","v","prüfen, besichtigen","Engineers inspect the bridge twice a year."],
["inspection","n","Inspektion, Prüfung","The inspection revealed several cracks."],
["inspiration","n","Inspiration, Anregung","The old market hall was his inspiration."],
["instinct","n","Instinkt","Her instinct told her to check the figures."],
["institutional","adj","institutionell","The problem is institutional, not personal."],
["instruct","v","anweisen, unterrichten","Staff were instructed to leave the building."],
["instrumental","adj","maßgeblich beteiligt","He was instrumental in securing the funding."],
["insufficient","adj","unzureichend","There was insufficient evidence to proceed."],
["insult","n,v","Beleidigung, beleidigen","The offer felt like an insult."],
["intact","adj","unversehrt, intakt","The foundations remained intact after the fire."],
["intake","n","Aufnahme, Zufluss","This year's intake of students is smaller."],
["integral","adj","wesentlich, integraler Bestandteil","Testing is an integral part of the process."],
["integrated","adj","integriert","They built an integrated transport system."],
["integration","n","Integration","Integration of the two teams took months."],
["integrity","n","Integrität, Unversehrtheit","The structural integrity was never in doubt."],
["intensify","v","verstärken, intensivieren","Criticism intensified after the report."],
["intensity","n","Intensität","The intensity of the storm surprised everyone."],
["intensive","adj","intensiv","The course involves two intensive weeks."],
["intent","n","Absicht","The original intent of the law was different."],
["interactive","adj","interaktiv","The museum has an interactive display."],
["interface","n","Schnittstelle","The interface between the two systems failed."],
["interfere","v","sich einmischen, stören","He refused to interfere in the dispute."],
["interference","n","Einmischung, Störung","Political interference delayed the decision."],
["interim","adj","vorläufig, Interims-","An interim report is due next month."],
["interior","n,adj","Innenraum, innen","The interior of the hall was completely rebuilt."],
["intermediate","adj","mittlere, Zwischen-","An intermediate support was added mid span."],
["intersection","n","Kreuzung, Schnittpunkt","The intersection is being redesigned."],
["intervene","v","eingreifen, intervenieren","The ministry intervened at the last moment."],
["intervention","n","Eingriff, Intervention","Early intervention prevented a collapse."],
["intimate","adj","vertraut, intim","She has an intimate knowledge of the region."],
["intriguing","adj","faszinierend, reizvoll","He put forward an intriguing alternative."],
["inventory","n","Bestand, Inventar","They took an inventory of all equipment."],
["investigator","n","Ermittler","Investigators examined the site for weeks."],
["invisible","adj","unsichtbar","The damage is almost invisible from outside."],
["invoke","v","sich berufen auf, anrufen","The city invoked an old building regulation."],
["involvement","n","Beteiligung","His involvement in the project ended early."],
["ironic","adj","ironisch","It is ironic that the safest route was rejected."],
["ironically","adv","ironischerweise","Ironically, the cheaper option lasted longer."],
["irony","n","Ironie","The irony was lost on the committee."],
["irrelevant","adj","irrelevant, belanglos","That objection is irrelevant here."],
["isolation","n","Isolation, Abgeschiedenheit","The village suffers from real isolation."]
],
"JK":[
["judicial","adj","gerichtlich, richterlich","The case is under judicial review."],
["jurisdiction","n","Zuständigkeit, Gerichtsbarkeit","The matter falls outside our jurisdiction."],
["just","adj","gerecht","Many felt it was not a just outcome."],
["justification","n","Rechtfertigung, Begründung","There was no justification for the delay."]
],
"L":[
["landlord","n","Vermieter","The landlord refused to repair the roof."],
["landmark","n","Wahrzeichen, Meilenstein","The tower is a landmark for the whole region."],
["lap","n","Runde, Schoß","He led for most of the final lap."],
["large-scale","adj","großangelegt","This is a large-scale infrastructure project."],
["latter","adj","letzterer","Of the two routes, the latter is cheaper."],
["lawmaker","n","Gesetzgeber, Abgeordneter","Lawmakers debated the bill for hours."],
["lawn","n","Rasen","The lawn in front of the office was replaced."],
["lawsuit","n","Klage, Gerichtsverfahren","The contractor faces a lawsuit over the delay."],
["layout","n","Anordnung, Grundriss","The layout of the office was changed."],
["leak","n,v","Leck, undicht sein","A leak in the roof damaged the archive."],
["leap","v","springen","Prices leapt after the announcement."],
["legacy","n","Vermächtnis, Erbe","The bridge is his lasting legacy."],
["legendary","adj","legendär","Her patience with clients was legendary."],
["legislation","n","Gesetzgebung","New legislation on noise takes effect in May."],
["legislative","adj","gesetzgebend","The legislative process took two years."],
["legislature","n","gesetzgebende Versammlung","The state legislature rejected the budget."],
["legitimate","adj","legitim, rechtmäßig","They raised several legitimate concerns."],
["lengthy","adj","langwierig, ausführlich","After a lengthy debate the plan was approved."],
["lesser","adj","geringer, kleiner","He chose the lesser of two evils."],
["lethal","adj","tödlich","The gas is lethal in high concentrations."],
["liable","adj","haftbar, anfällig","The owner is liable for any damage."],
["liability","n","Haftung, Belastung","The old building became a financial liability."],
["liberal","adj,n","liberal, freigiebig","They took a liberal view of the rules."],
["liberation","n","Befreiung","The liberation of the city is marked each May."],
["liberty","n","Freiheit","He took the liberty of changing the schedule."],
["lifelong","adj","lebenslang","She had a lifelong interest in bridges."],
["likelihood","n","Wahrscheinlichkeit","There is little likelihood of further delay."],
["limb","n","Gliedmaße, Ast","He lost the use of a limb in the accident."],
["linear","adj","linear","The relationship is not strictly linear."],
["line-up","n","Aufstellung, Besetzung","The line-up of speakers was impressive."],
["linger","v","verweilen, anhalten","Doubts about the design still linger."],
["listing","n","Auflistung, Eintrag","The building received a heritage listing."],
["lobby","n,v","Lobby, Einfluss nehmen","Farmers lobbied hard against the tax."],
["logic","n","Logik","There is a certain logic to their approach."],
["long-standing","adj","langjährig","They have a long-standing agreement."],
["long-time","adj","langjährig","He is a long-time critic of the plan."],
["loom","v","sich abzeichnen, drohen","A funding crisis loomed over the project."],
["loop","n","Schleife","The road makes a wide loop around the lake."],
["loyalty","n","Loyalität, Treue","Staff loyalty kept the firm alive."]
],
"M":[
["machinery","n","Maschinen, Apparat","The machinery was replaced after twenty years."],
["magical","adj","magisch, zauberhaft","The old town has a magical atmosphere at night."],
["magnetic","adj","magnetisch","The sensor uses a magnetic field."],
["magnitude","n","Ausmaß, Größenordnung","Nobody grasped the magnitude of the task."],
["mainland","n","Festland","Supplies come daily from the mainland."],
["mainstream","n,adj","Mainstream, verbreitet","The idea has entered mainstream thinking."],
["maintenance","n","Wartung, Instandhaltung","Maintenance costs rose sharply."],
["mandate","n","Mandat, Auftrag","The agency has a clear mandate to act."],
["mandatory","adj","verpflichtend","Helmets are mandatory on every site."],
["manifest","v","zeigen, offenbaren","The fault manifested only under heavy load."],
["manipulate","v","manipulieren","The figures had been manipulated."],
["manipulation","n","Manipulation","Market manipulation is a criminal offence."],
["manuscript","n","Manuskript","The manuscript lay unread for decades."],
["march","n,v","Marsch, marschieren","Thousands marched through the city."],
["marginal","adj","geringfügig, marginal","The savings were marginal at best."],
["marine","adj","Meeres-, maritim","The project studies marine sediment."],
["marketplace","n","Marktplatz, Markt","The firm struggles in a crowded marketplace."],
["massacre","n","Massaker","A memorial marks the site of the massacre."],
["mathematical","adj","mathematisch","The model rests on a mathematical assumption."],
["mature","adj","reif, ausgereift","The technology is now fairly mature."],
["maximise","v","maximieren","They aimed to maximise usable floor space."],
["meaningful","adj","sinnvoll, bedeutungsvoll","We need a meaningful discussion, not slogans."],
["meantime","n","Zwischenzeit","In the meantime, work continues on site."],
["medieval","adj","mittelalterlich","The medieval wall was carefully restored."],
["meditation","n","Meditation","He starts every day with meditation."],
["melody","n","Melodie","A simple melody ran through the whole piece."],
["memo","n","Notiz, Mitteilung","A short memo explained the change."],
["memoir","n","Memoiren, Erinnerungen","Her memoir describes life on site."],
["memorial","n","Denkmal, Gedenkstätte","A memorial was built near the old mine."],
["mentor","n","Mentor","His mentor encouraged him to specialise."],
["merchant","n","Händler, Kaufmann","The house belonged to a wool merchant."],
["mercy","n","Gnade, Barmherzigkeit","They were at the mercy of the weather."],
["mere","adj","bloß, rein","A mere ten percent of bids were accepted."],
["merely","adv","lediglich, bloß","He merely repeated what everyone knew."],
["merge","v","fusionieren, verschmelzen","The two departments merged last year."],
["merger","n","Fusion","The merger created the largest firm in the sector."],
["merit","n","Verdienst, Vorzug","The proposal has considerable merit."],
["in the midst of","prep","inmitten von","The talks collapsed in the midst of a crisis."],
["migration","n","Migration, Wanderung","Migration to the cities continues."],
["militant","n,adj","militant, Kämpfer","A militant faction rejected the deal."],
["militia","n","Miliz","A local militia controlled the bridge."],
["minimal","adj","minimal","The change had minimal effect on costs."],
["minimise","v","minimieren","The design minimises heat loss."],
["mining","n","Bergbau","Mining shaped the whole valley."],
["ministry","n","Ministerium","The ministry approved the funding."],
["minute","adj","winzig","A minute crack ran along the beam."],
["miracle","n","Wunder","It was a miracle that nobody was hurt."],
["misery","n","Elend, Not","The flood brought misery to the whole area."],
["misleading","adj","irreführend","The chart was highly misleading."],
["mismanagement","n","Misswirtschaft","Years of mismanagement ruined the firm."],
["missile","n","Rakete, Geschoss","The missile missed its target."],
["mob","n","Mob, Meute","An angry mob gathered outside the gate."],
["mobility","n","Mobilität, Beweglichkeit","Urban mobility is the theme of the conference."],
["mobilise","v","mobilisieren","The union mobilised its members quickly."],
["moderate","adj","gemäßigt, mäßig","Growth has been moderate this year."],
["modification","n","Änderung, Modifikation","A small modification improved the flow."],
["module","n","Modul","Each module is delivered ready to install."],
["momentum","n","Schwung, Dynamik","The campaign lost momentum in the autumn."],
["monk","n","Mönch","A monk showed us the old library."],
["monopoly","n","Monopol","The company had a monopoly for decades."],
["morality","n","Moral","The debate turned into a question of morality."],
["motive","n","Beweggrund, Motiv","His motive for leaving remains unclear."],
["municipal","adj","städtisch, kommunal","Municipal waste collection was reorganised."],
["mutual","adj","gegenseitig","The agreement rests on mutual trust."]
],
"N":[
["naive","adj","naiv","It was naive to expect no objections."],
["namely","adv","nämlich","One thing worries me, namely the cost."],
["nationwide","adj,adv","landesweit","The scheme was rolled out nationwide."],
["naval","adj","Marine-, See-","The old naval yard is now a park."],
["neglect","v","vernachlässigen","The building was neglected for years."],
["neighbouring","adj","benachbart","Neighbouring towns share the same supply."],
["newsletter","n","Rundbrief, Newsletter","The newsletter goes out every Friday."],
["niche","n","Nische","The firm found a profitable niche."],
["noble","adj","edel, nobel","It was a noble aim but hard to fund."],
["nod","v","nicken","She nodded and signed the drawing."],
["nominate","v","nominieren, benennen","He was nominated for the design award."],
["nomination","n","Nominierung","Her nomination surprised nobody."],
["nominee","n","Nominierter, Kandidat","The nominee withdrew a week later."],
["nonetheless","adv","dennoch, trotzdem","The plan is costly, nonetheless it is necessary."],
["non-profit","adj","gemeinnützig","A non-profit body runs the archive."],
["nonsense","n","Unsinn","He dismissed the claim as nonsense."],
["norm","n","Norm, Regel","Remote meetings have become the norm."],
["notable","adj","bemerkenswert","There was one notable exception."],
["notably","adv","insbesondere, bemerkenswert","Costs rose, notably for steel."],
["notify","v","benachrichtigen","Residents must be notified in writing."],
["notorious","adj","berüchtigt","The crossing is notorious among cyclists."],
["nursery","n","Kindergarten, Gärtnerei","A nursery opened on the ground floor."]
],
"O":[
["objection","n","Einwand","Only one objection was raised."],
["oblige","v","verpflichten","The contract obliges us to finish by June."],
["obsess","v","besessen sein","He obsesses over tiny details."],
["obsession","n","Besessenheit","Punctuality became an obsession for him."],
["occasional","adj","gelegentlich","There were occasional problems with the pump."],
["occurrence","n","Vorkommnis, Auftreten","Flooding is now a regular occurrence."],
["odds","n","Chancen, Wahrscheinlichkeit","The odds of finishing on time are poor."],
["offering","n","Angebot, Darbietung","Their latest offering impressed the jury."],
["offspring","n","Nachkommen","The birds return to feed their offspring."],
["operational","adj","betriebsbereit, betrieblich","The plant is fully operational again."],
["opt","v","sich entscheiden für","Most clients opt for the cheaper finish."],
["optimism","n","Optimismus","There is cautious optimism about the budget."],
["oral","adj","mündlich","The exam includes an oral part."],
["organisational","adj","organisatorisch","The delay was purely organisational."],
["orientation","n","Orientierung, Ausrichtung","The orientation of the building saves energy."],
["originate","v","entstehen, stammen","The idea originated in a student project."],
["outbreak","n","Ausbruch","An outbreak of fire closed the workshop."],
["outing","n","Ausflug","The team went on an outing to the quarry."],
["outlet","n","Abfluss, Verkaufsstelle","The outlet was blocked by debris."],
["outlook","n","Aussichten, Einstellung","The outlook for the sector is uncertain."],
["outrage","n","Empörung","The decision caused public outrage."],
["outsider","n","Außenseiter","An outsider won the competition."],
["overlook","v","übersehen, überblicken","They overlooked a crucial detail."],
["overly","adv","übermäßig","The estimate was overly optimistic."],
["oversee","v","beaufsichtigen","She oversees three construction sites."],
["overturn","v","aufheben, umstoßen","The court overturned the earlier ruling."],
["overwhelm","v","überwältigen","Staff were overwhelmed by complaints."],
["overwhelming","adj","überwältigend","There was overwhelming support for the plan."]
],
"P":[
["parameter","n","Parameter, Rahmenbedingung","The parameters of the study were set early."],
["parental","adj","elterlich","Parental consent is required for the trip."],
["partial","adj","teilweise, parteiisch","Only a partial refund was offered."],
["partially","adv","teilweise","The road is partially blocked by scaffolding."],
["passing","n,adj","Vorübergehen, flüchtig","He mentioned the problem only in passing."],
["passive","adj","passiv","The building uses passive cooling."],
["pastor","n","Pfarrer","The pastor opened the new community hall."],
["patent","n","Patent","They filed a patent for the joint design."],
["pathway","n","Weg, Pfad","There is no clear pathway into the profession."],
["patrol","n,v","Streife, patrouillieren","Guards patrol the site at night."],
["patron","n","Förderer, Gönner","A wealthy patron paid for the restoration."],
["peak","n","Gipfel, Höhepunkt","Traffic reaches its peak at eight."],
["peasant","n","Bauer, Landarbeiter","The land was farmed by peasants for centuries."],
["peculiar","adj","eigenartig, eigentümlich","The crack had a peculiar shape."],
["persist","v","fortbestehen, beharren","The leak persisted despite three repairs."],
["persistent","adj","hartnäckig, anhaltend","Persistent rain delayed the concrete pour."],
["personnel","n","Personal","Trained personnel operate the crane."],
["petition","n","Petition","Six thousand people signed the petition."],
["philosopher","n","Philosoph","He quoted a Greek philosopher in the report."],
["philosophical","adj","philosophisch","She took a philosophical view of the setback."],
["pioneer","n","Pionier, Wegbereiter","He was a pioneer of prestressed concrete."],
["pipeline","n","Rohrleitung, Pipeline","A new pipeline supplies the eastern district."],
["pit","n","Grube, Kuhle","The pit was fenced off during works."],
["plausible","adj","plausibel, glaubhaft","That is the only plausible explanation."],
["plea","n","Bitte, Plädoyer","His plea for more time was rejected."],
["plead","v","flehen, plädieren","She pleaded for a delay of two weeks."],
["pledge","n,v","Zusage, geloben","The city pledged funding for ten years."],
["plunge","n,v","Sturz, stürzen","Share prices plunged after the announcement."],
["pole","n","Mast, Pol","A wooden pole carried the power line."],
["poll","n","Umfrage","A recent poll showed strong opposition."],
["portfolio","n","Portfolio, Mappe","The firm has a broad portfolio of projects."],
["portray","v","darstellen, schildern","The film portrays engineers as heroes."],
["postpone","v","verschieben","The opening was postponed until spring."],
["post-war","adj","Nachkriegs-","Most of the district is post-war housing."],
["practitioner","n","Praktiker, Fachmann","The guide is written for practitioners."],
["preach","v","predigen","He preaches caution on every project."],
["precede","v","vorausgehen","A long consultation preceded the decision."],
["precedent","n","Präzedenzfall","The ruling sets an important precedent."],
["precision","n","Präzision","The parts were cut with great precision."],
["predator","n","Raubtier","The wolf is the main predator in the area."],
["predecessor","n","Vorgänger","His predecessor left the accounts in disorder."],
["predominantly","adv","überwiegend","The area is predominantly residential."],
["pregnancy","n","Schwangerschaft","She continued working through her pregnancy."],
["prejudice","n","Vorurteil","Old prejudices still shape hiring decisions."],
["preliminary","adj","vorläufig, einleitend","Preliminary results look promising."],
["premier","n","Ministerpräsident","The regional premier opened the tunnel."],
["premise","n","Prämisse, Voraussetzung","The plan rests on a false premise."],
["premium","n","Prämie, Aufpreis","Clients pay a premium for faster delivery."],
["prescribe","v","verschreiben, vorschreiben","The code prescribes a minimum thickness."],
["prescription","n","Rezept, Vorschrift","There is no simple prescription for this."],
["presently","adv","derzeit, bald","The bridge is presently closed to lorries."],
["preservation","n","Erhaltung, Bewahrung","The preservation of the facade was required."],
["preside","v","den Vorsitz führen","She presided over the inquiry."],
["presidency","n","Präsidentschaft","His presidency lasted only two years."],
["prestigious","adj","angesehen, prestigeträchtig","They won a prestigious design award."],
["presumably","adv","vermutlich","The delay was presumably caused by weather."],
["presume","v","annehmen, vermuten","I presume the drawings are final."],
["prevail","v","sich durchsetzen, vorherrschen","Common sense finally prevailed."],
["prevalence","n","Verbreitung, Häufigkeit","The prevalence of damp surprised the surveyor."],
["prevention","n","Vorbeugung, Verhütung","Prevention is cheaper than repair."],
["prey","n","Beute","The owl hunts small prey at night."],
["privatization","n","Privatisierung","Privatization of the water supply was reversed."],
["privilege","n","Privileg, Vorrecht","Parking on site is a privilege, not a right."],
["probe","n,v","Untersuchung, untersuchen","Investigators probed the cause of the fire."],
["problematic","adj","problematisch","The soil conditions proved problematic."],
["proceeding","n","Verfahren, Vorgang","Legal proceedings began in March."],
["proceeds","n","Erlös, Einnahmen","The proceeds went to a local charity."],
["processing","n","Verarbeitung","Data processing takes about an hour."],
["processor","n","Prozessor, Verarbeiter","The processor overheated under load."],
["proclaim","v","verkünden, erklären","The mayor proclaimed the project a success."],
["productive","adj","produktiv, ergiebig","It was a short but productive meeting."],
["productivity","n","Produktivität","Productivity fell during the heatwave."],
["profitable","adj","rentabel, gewinnbringend","The line has never been profitable."],
["profound","adj","tiefgreifend","The reform had a profound effect on the trade."],
["projection","n","Prognose, Projektion","Their cost projection was far too low."],
["prominent","adj","prominent, hervorstechend","A prominent crack ran across the slab."],
["pronounced","adj","ausgeprägt, deutlich","There is a pronounced slope towards the river."],
["propaganda","n","Propaganda","The posters were pure propaganda."],
["proposition","n","Vorschlag, Angebot","It is an attractive proposition for investors."],
["prosecute","v","strafrechtlich verfolgen","Offenders will be prosecuted."],
["prosecution","n","Strafverfolgung, Anklage","The prosecution called three witnesses."],
["prosecutor","n","Staatsanwalt","The prosecutor asked for a longer sentence."],
["prospective","adj","zukünftig, potenziell","Prospective buyers toured the site."],
["prosperity","n","Wohlstand","The harbour brought prosperity to the town."],
["protective","adj","schützend, Schutz-","A protective coating prevents corrosion."],
["protocol","n","Protokoll, Verfahrensweise","A strict safety protocol is in place."],
["province","n","Provinz","The province funds most local roads."],
["provincial","adj","provinziell, Provinz-","The provincial government approved the budget."],
["provision","n","Bereitstellung, Bestimmung","The contract has a provision for delays."],
["provoke","v","provozieren, auslösen","The decision provoked immediate protest."],
["psychiatric","adj","psychiatrisch","He was referred for psychiatric assessment."],
["pulse","n","Puls, Impuls","The device sends a short electrical pulse."]
],
"Q":[
["query","n","Anfrage, Rückfrage","Send any query to the site office."],
["quest","n","Suche, Streben","The quest for cheaper materials continues."],
["quota","n","Quote, Kontingent","Each region was given a housing quota."]
],
"R":[
["radical","adj","radikal","They proposed a radical redesign."],
["rage","n","Wut, Zorn","His rage faded once the facts were clear."],
["raid","n,v","Razzia, überfallen","Police raided the warehouse at dawn."],
["rally","n,v","Kundgebung, sich sammeln","A rally was held outside the town hall."],
["ranking","n","Rangliste","The university climbed in the ranking."],
["ratio","n","Verhältnis","The ratio of sand to cement was wrong."],
["rational","adj","rational, vernünftig","There is a rational explanation for the cracks."],
["ray","n","Strahl","A ray of light fell through the shaft."],
["readily","adv","bereitwillig, leicht","The parts are readily available."],
["realization","n","Erkenntnis, Verwirklichung","The realization came too late to help."],
["realm","n","Bereich, Reich","That belongs to the realm of theory."],
["rear","n,adj","Rückseite, hinten","The rear entrance stays locked at night."],
["reasoning","n","Argumentation, Überlegung","His reasoning convinced the committee."],
["reassure","v","beruhigen","The engineer reassured the residents."],
["rebel","n","Rebell","A few rebels refused to sign."],
["rebellion","n","Aufstand, Rebellion","The rebellion lasted only three weeks."],
["recipient","n","Empfänger","Each recipient must sign for the parcel."],
["reconstruction","n","Wiederaufbau, Rekonstruktion","Reconstruction of the station took four years."],
["recount","v","schildern, nacherzählen","He recounted the events of that night."],
["recruitment","n","Einstellung, Rekrutierung","Recruitment of skilled workers is difficult."],
["referendum","n","Volksabstimmung","The tunnel was approved by referendum."],
["reflection","n","Spiegelung, Überlegung","On reflection, the earlier design was better."],
["reform","n,v","Reform, reformieren","The planning system was reformed in 2019."],
["refuge","n","Zuflucht","The hut served as a refuge in bad weather."],
["refusal","n","Weigerung, Ablehnung","His refusal to sign delayed everything."],
["regain","v","zurückgewinnen","The firm slowly regained its reputation."],
["regardless","adv","ungeachtet, trotzdem","Work continued regardless of the weather."],
["regime","n","Regime, System","The old regime collapsed within days."],
["regulator","n","Aufsichtsbehörde, Regler","The regulator fined the company heavily."],
["regulatory","adj","aufsichtsrechtlich","Regulatory approval took eighteen months."],
["rehabilitation","n","Sanierung, Rehabilitation","Rehabilitation of the old sewers begins soon."],
["reign","n,v","Herrschaft, regieren","Her reign over the department lasted decades."],
["rejection","n","Ablehnung","The rejection of the bid came without reasons."],
["relevance","n","Relevanz, Bedeutung","The study has little relevance for our case."],
["reliability","n","Zuverlässigkeit","Reliability matters more than speed here."],
["reluctant","adj","widerwillig, zögernd","He was reluctant to change the design."],
["remainder","n","Rest","The remainder of the budget goes on landscaping."],
["remains","n","Überreste","The remains of a Roman wall were found."],
["remedy","n","Abhilfe, Mittel","There is no quick remedy for subsidence."],
["reminder","n","Erinnerung, Mahnung","The crack is a reminder of the old fault."],
["removal","n","Entfernung, Beseitigung","Removal of the asbestos cost a fortune."],
["render","v","machen, erbringen","The damage rendered the flat uninhabitable."],
["renew","v","erneuern, verlängern","The licence must be renewed annually."],
["renowned","adj","renommiert, berühmt","The firm is renowned for its bridges."],
["rental","n","Miete, Vermietung","Rental income covers the maintenance."],
["replacement","n","Ersatz","A replacement pump arrived the next day."],
["reportedly","adv","Berichten zufolge","The cost has reportedly doubled."],
["representation","n","Vertretung, Darstellung","Residents demanded better representation."],
["reproduce","v","reproduzieren, sich fortpflanzen","The test could not be reproduced."],
["reproduction","n","Reproduktion, Nachbildung","The window is a faithful reproduction."],
["republic","n","Republik","The republic was founded after the war."],
["resemble","v","ähneln","The new hall resembles a warehouse."],
["reside","v","wohnen, liegen in","The problem resides in the foundations."],
["residence","n","Wohnsitz, Residenz","He took up residence near the site."],
["residential","adj","Wohn-, Wohngebiets-","The street is purely residential."],
["residue","n","Rückstand","A grey residue remained on the surface."],
["resignation","n","Rücktritt, Kündigung","His resignation surprised the whole office."],
["resistance","n","Widerstand","There was strong resistance to the route."],
["respective","adj","jeweilig","They returned to their respective offices."],
["respectively","adv","beziehungsweise","Costs rose by five and ten percent respectively."],
["restoration","n","Restaurierung, Wiederherstellung","The restoration of the chapel took years."],
["restraint","n","Zurückhaltung, Beschränkung","He showed remarkable restraint in the meeting."],
["resume","v","wieder aufnehmen","Work resumed after the inspection."],
["retreat","n,v","Rückzug, sich zurückziehen","The company retreated from the foreign market."],
["retrieve","v","abrufen, zurückholen","We retrieved the old drawings from the archive."],
["revelation","n","Enthüllung, Offenbarung","The revelation ended his career."],
["revenge","n","Rache","He acted out of revenge, not principle."],
["reverse","v","umkehren, rückgängig machen","The council reversed its earlier decision."],
["revival","n","Wiederbelebung","The area is enjoying an economic revival."],
["revive","v","wiederbeleben","Plans for the tram were revived last year."],
["revolutionary","adj,n","revolutionär","The method was revolutionary at the time."],
["rhetoric","n","Rhetorik","There was plenty of rhetoric but little action."],
["riot","n","Aufruhr, Krawall","A riot broke out after the announcement."],
["rip","v","zerreißen","The wind ripped the sheeting from the frame."],
["ritual","n","Ritual","The morning briefing became a ritual."],
["robust","adj","robust, belastbar","The design is robust enough for heavy loads."],
["rod","n","Stange, Stab","A steel rod reinforces the joint."],
["rookie","n","Neuling","The rookie made a costly mistake."],
["roster","n","Dienstplan","The roster is published every Friday."],
["rotate","v","drehen, rotieren","Staff rotate between the two sites."],
["rotation","n","Drehung, Rotation","The rotation of the crane is limited."],
["ruling","n,adj","Urteil, herrschend","The court ruling favoured the tenants."],
["rumour","n","Gerücht","A rumour spread that the site would close."]
],
"U":[
["unconstitutional","adj","verfassungswidrig","The court declared the law unconstitutional."],
["undergraduate","n","Bachelorstudent","The lecture is aimed at undergraduates."],
["underlying","adj","zugrunde liegend","The underlying cause was poor drainage."],
["undermine","v","untergraben, unterhöhlen","Constant delays undermined public trust."],
["undoubtedly","adv","zweifellos","This is undoubtedly the cheaper option."],
["unify","v","vereinen, vereinheitlichen","The reform unified three separate agencies."],
["unprecedented","adj","beispiellos","Costs rose at an unprecedented rate."],
["unveil","v","enthüllen, vorstellen","The city unveiled plans for a new quarter."],
["upcoming","adj","bevorstehend","The upcoming inspection worries the site manager."],
["upgrade","v","aufrüsten, verbessern","The heating system will be upgraded."],
["uphold","v","aufrechterhalten, bestätigen","The appeal court upheld the original ruling."],
["utility","n","Versorgungsbetrieb, Nutzen","The utility company laid a new main."],
["utilise","v","nutzen, verwerten","The design utilises waste heat from the plant."],
["utterly","adv","völlig, zutiefst","The estimate was utterly unrealistic."]
],
"V":[
["vacuum","n","Vakuum, Leere","His departure left a vacuum in the team."],
["vague","adj","vage, unbestimmt","The brief was frustratingly vague."],
["validity","n","Gültigkeit","Nobody questioned the validity of the test."],
["vanish","v","verschwinden","The old workshops vanished within a decade."],
["variable","n,adj","Variable, veränderlich","Rainfall is the most variable factor."],
["varied","adj","abwechslungsreich, unterschiedlich","The response from residents was varied."],
["vein","n","Vene, Ader","A vein of harder rock crossed the tunnel."],
["venture","n","Unternehmung, Wagnis","The joint venture lasted only two years."],
["verbal","adj","mündlich, verbal","A verbal agreement is not enough here."],
["verdict","n","Urteil","The verdict came after three days."],
["verify","v","überprüfen, bestätigen","We verified every measurement on site."],
["verse","n","Vers, Strophe","He quoted a verse at the opening."],
["versus","prep","gegen, im Vergleich zu","It is cost versus durability once again."],
["vessel","n","Schiff, Gefäß","A supply vessel docked overnight."],
["veteran","n","Veteran","A veteran of forty projects led the team."],
["viable","adj","tragfähig, machbar","Only one route is economically viable."],
["vibrant","adj","lebendig, pulsierend","The quarter has a vibrant street life."],
["vice","n","Laster, Untugend","Impatience was his only real vice."],
["vicious","adj","bösartig, brutal","The campaign turned vicious."],
["violate","v","verletzen, verstoßen gegen","The work violated several safety rules."],
["violation","n","Verstoß, Verletzung","Each violation carries a heavy fine."],
["virtue","n","Tugend, Vorzug","Patience is a virtue on this site."],
["vocal","adj","lautstark, stimmlich","Neighbours were vocal in their opposition."],
["vow","v","geloben, schwören","He vowed never to work weekends again."],
["vulnerability","n","Anfälligkeit, Verwundbarkeit","The survey exposed the building's vulnerability."],
["vulnerable","adj","anfällig, verwundbar","Older bridges are especially vulnerable to salt."]
],
"W":[
["ward","n","Station, Bezirk","The hospital opened a new ward."],
["warehouse","n","Lagerhalle","The warehouse was converted into flats."],
["warfare","n","Kriegsführung","The museum documents trench warfare."],
["warrant","n,v","Haftbefehl, rechtfertigen","The findings warrant a full investigation."],
["warrior","n","Krieger","The statue shows a mounted warrior."],
["weaken","v","schwächen","Frost weakened the mortar joints."],
["weave","v","weben, flechten","The path weaves between the old sheds."],
["weed","n","Unkraut","Weeds grew through the cracked surface."],
["well","n","Brunnen","The village still uses an old well."],
["well-being","n","Wohlbefinden","Site conditions affect worker well-being."],
["whatsoever","adv","überhaupt","There was no evidence whatsoever."],
["whip","v","peitschen","The wind whipped across the open deck."],
["wholly","adv","gänzlich, völlig","The claim is wholly without foundation."],
["widen","v","verbreitern, erweitern","The junction will be widened next year."],
["width","n","Breite","The width of the lane is only three metres."],
["willingness","n","Bereitschaft","Their willingness to compromise saved the deal."],
["wipe","v","abwischen","One storm wiped out a month of progress."],
["wit","n","Witz, Geist","He answered with characteristic wit."],
["withdrawal","n","Rückzug, Abhebung","The withdrawal of funding stopped the work."],
["workout","n","Training","She fits a workout in before the site meeting."],
["worship","n,v","Verehrung, anbeten","The building was used for worship until 1970."],
["worthwhile","adj","lohnenswert","The extra survey proved worthwhile."],
["worthy","adj","würdig, wert","It is a worthy successor to the old hall."],
["wrongdoing","n","Fehlverhalten, Vergehen","The audit found no wrongdoing."]
],
"Y":[
["yield","v","nachgeben, erbringen","The soil yields under heavy load."]
]
};
